- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        upgrade: yes
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
