- name: install cron job (ansible-pull)
  cron:
    user: gord
    name: "gord provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -U https://github.com/bayview-gord/ansible-desktop.git > /dev/null"
