- name: Install dependencies for Ansible apt* modules
  args:
    warn: no
  register: telegraf_apt_dependencies_installed
  changed_when: "'is already the newest version' not in telegraf_apt_dependencies_installed.stdout"
  environment:
    LANG: en_US.UTF-8
    LC_MESSAGES: en_US.UTF-8
    LC_ALL: en_US.UTF-8
  tags:
    - telegraf-repository-key
    - telegraf-repository

- name: Install apt-key dependency (gnupg)
  apt:
    package: gnupg
  tags:
    - telegraf-repository-key
    - telegraf-repository
