- name: create user gord
  user:
    name: gord
    system: yes

- name: copy sudoers_gord
  copy:
    src: files/sudoers_gord
    dest: /etc/sudoers.d/gord
    owner: root
    group: root
    mode: 0400
